### ISSUE TITLE
Suggest rename of "login" command to "signin"

### ISSUE THREAD

**Issue by russmiles** [chaosiq/chaostoolkit-cloud#10]
`login` feels slightly clunky, and maybe a little antiquated. Instead `signin` seems better, and also seems semantically more correct as you are signing your chaos toolkit installation into your Chaos Toolkit Cloud account, as well as now specifying the current organisation context.

**Comment by russmiles** [comment]
Wdyt @Lawouach ?

**Comment by Lawouach** [comment]
Agreed indeed. `login` never sounded right to me.
