### ISSUE TITLE
Add new operation to switch "organisation" or "context"

### ISSUE THREAD

**Issue by russmiles** [chaosiq/chaostoolkit-cloud#11]
It should be possible to switch the default context without having to sign-in again. Currently the context is just the current organisation, but maybe there will be more context eventually? Either way, maybe a "set-context" command is required, a la `kubectl` (but perhaps without it being a sub-command?):

https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-context-and-configuration

**Comment by Lawouach** [comment]
What about something like:

```
$ chaos use-org ORGNAME
```
?

**Comment by russmiles** [comment]
Certainly more meaningful. Wdyt @mperrien ?

**Comment by russmiles** [comment]
I'll move forward with `use-org` for now, we can always change it prior to release.

**Comment by russmiles** [comment]
I think with the "use-org" command in, we might be ready for a new release of this extension _and_ corresponding docker images.

**Comment by russmiles** [comment]
This work will refine "sign-in" so that only one org is recorded, the default and current one. This will mean removing the "default" specification in the settings, as it will be the only org recorded there.

This means "sign-in" will simply be a combination of recording and testing the CTK Cloud and token with the "use-org" functionality then being invoked.

**Comment by russmiles** [comment]
I've settled on "org" for now as the command.
